name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    # Set an environment variable for the timestamp
    env:
      IMAGE_TAG: trading-tracker-${{ github.run_id }}

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -f ./server/Dockerfile ./server --tag $IMAGE_TAG

      # Login to Digital Ocean Container Registry
      - name: Login to Digital Ocean Container Registry
        run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | docker login registry.digitalocean.com -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      # Tag the image for the registry
      - name: Tag the Docker image
        run: docker tag $IMAGE_TAG registry.digitalocean.com/${{ secrets.CONTAINER_REGISTRY }}/$IMAGE_TAG

      # Push the image to the registry
      - name: Push the Docker image to the registry
        run: docker push registry.digitalocean.com/${{ secrets.CONTAINER_REGISTRY }}/$IMAGE_TAG
